"""create metrics table

Revision ID: 9059e35d3703
Revises: 9fd5fa2b5328
Create Date: 2026-09-28 20:02:44.569451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9059e35d3703'
down_revision: Union[str, Sequence[str], None] = '9fd5fa2b5328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cpu_percent', sa.Double(), nullable=True),
    sa.Column('memory_used_bytes', sa.BigInteger(), nullable=True),
    sa.Column('memory_total_bytes', sa.BigInteger(), nullable=True),
    sa.Column('disk_used_bytes', sa.BigInteger(), nullable=True),
    sa.Column('disk_total_bytes', sa.BigInteger(), nullable=True),
    sa.Column('services', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metrics_device_collected_at', 'metrics', ['device_id', 'collected_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metrics_device_collected_at', table_name='metrics')
    op.drop_table('metrics')
    # ### end Alembic commands ###
