"""replace disk columns with disks jsonb

Revision ID: 97300bd3dc58
Revises: c6f729b1d410
Create Date: 2026-10-01 17:24:06.454034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97300bd3dc58'
down_revision: Union[str, Sequence[str], None] = 'c6f729b1d410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('disks', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True))
    op.drop_column('metrics', 'disk_total_bytes')
    op.drop_column('metrics', 'disk_used_bytes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('disk_used_bytes', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('metrics', sa.Column('disk_total_bytes', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('metrics', 'disks')
    # ### end Alembic commands ###
