"""add agent token hash

Revision ID: 9fd5fa2b5328
Revises: 2e33ea4e5116
Create Date: 2026-09-25 13:29:16.355552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fd5fa2b5328'
down_revision: Union[str, Sequence[str], None] = '2e33ea4e5116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'devices',
        sa.Column(
            'agent_token_hash',
            sa.String(
                length=64),
            nullable=True))
    op.create_unique_constraint(
        "uq_devices_agent_token_hash", "devices", ["agent_token_hash"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(
        "uq_devices_agent_token_hash", "devices", type_="unique"
    )
    op.drop_column('devices', 'agent_token_hash')
    # ### end Alembic commands ###
